### ISSUE TITLE
Utworzenie federata stolików

### ISSUE THREAD

**Issue by ventaquil** [TeamCrypt/MiTSK-Projekt#8]
Do zrobienia:
* Utworzenie federata stolików: `mitsk.tables.Federate`
* Utworzenie ambasadora federatu
* Utworzenie odpowiedniego pliku FOM (może być minimalny do tego zadania)
* Tworzenie sparametryzowanej liczby stolików (parametr to stała)
* Stworzenie odpowiednich obiektów i interakcji zapewniających zajmowanie stolika przez klienta i zwalnianie go po losowym czasie
* Podczas zajmowania stolika usuwanie klienta z kolejki
* Usuwanie obiektu klienta po zwolnieniu stolika

**Comment by ventaquil** [comment]
Nie trzeba na razie robić statystyk z tego - do tego będzie osobny _issue_.

**Comment by malete** [comment]
Utworzono:
- Federata i Ambasadora stolików
- plik FOM
- parametryzowaną ilość stolików
- obiekty Klienta i Stolika
- interakcje zajmowania i zwalniania stolika przez klienta po losowym czasie

**Comment by malete** [comment]
Przetestowano komunikację federatów:
- wysyłanie i odbieranie klientów pomiędzy federatami Klientów i Kolejki
- powiadamianie Kolejki o wolnych Stolikach
- przesyłanie Klientów do wolnych Stolików

**Comment by ventaquil** [comment]
Zrobiłem _merge_
